### PR TITLE
build docker image for amd64 and arm64

### PR DESCRIPTION
**Pull request by artyorsh**
Thanks for the app! Unfortunately can't run it on Raspberry Pi, hope it becomes possible with this change.

### CODE REVIEW

**Comment by kamilkosek** [comment]
I will first merge this PR into the dev branch. Otherwise a new latest build will be started and this may be very confusing ;)

**Comment by kamilkosek** [comment]
The build has completed, maybe you can try it ? 
[https://github.com/kamilkosek/jellyplist/pkgs/container/jellyplist/317164789?tag=dev](https://github.com/kamilkosek/jellyplist/pkgs/container/jellyplist/317164789?tag=dev)

**Comment by artyorsh** [comment]
> The build has completed, maybe you can try it ? https://github.com/kamilkosek/jellyplist/pkgs/container/jellyplist/317164789?tag=dev

At the first sight runs well :) Will come with more details if something pops up

**Comment by artyorsh** [comment]
Hey @kamilkosek just FYI, I've done the full setup and have synchronised a few playlists. Works good on ARM, and I did not see anything suspicious in logs as well --> I think it can be safely merged into main?

Below attaching a few screenshots from the app running on Raspberry PI 5. Thanks again for all the work you put into the app! 

image
image
image

**Comment by kamilkosek** [comment]
YESSSS!! I totally love to see screenshots on how people use it 🤟  
It´s already been merged  😉

**Pull request merged**
